import React,{useCallback,useEffect,useMemo,useRef,useState} from "react";
import ReactFlow,{addEdge,applyEdgeChanges,applyNodeChanges,Background,Controls,EdgeLabelRenderer,getBezierPath,Position,useReactFlow} from "reactflow";
import "reactflow/dist/style.css";
import {useContext} from "react";
import {AuthContext} from "../../context/AuthContext";
import {nodeTypes} from "./nodeTypes";
import {resolveTheme,THEMES} from "./themes";
import {salvarMapa,salvarConfiguracaoMapa,getConfiguracoes} from "../../services/mapasApi";
import {atualizarPreferenciasUsuario} from "../../services/usuarioApi";

const EDGE_STYLE={stroke:"rgba(255,255,255,.72)",strokeWidth:2};
const IMAGE_MAX_BYTES=4*1024*1024,HISTORY_LIMIT=80,DATA_HISTORY_DELAY=650;
const isInput=e=>{const t=e?.target;return ["input","textarea","button"].includes(t?.tagName?.toLowerCase())||t?.isContentEditable};
const uid=p=>window.crypto?.randomUUID?.()||`${p}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const cleanData=(d={})=>Object.fromEntries(Object.entries(d).filter(([k])=>!["onChange","onEditEnd","onResize","onResizeStart","onResizeEnd","editing","isSelected","accentColor","imageDeformable"].includes(k)));
const payload=(nodes,edges)=>({nodes:nodes.map(n=>({id:n.id,type:n.type||"TEXT",position:n.position,data:cleanData(n.data)})),edges:edges.map(e=>({id:e.id,source:e.source,target:e.target,sourceHandle:e.sourceHandle||"right-source",targetHandle:e.targetHandle||"left-target",label:e.label||""}))});
const clone=v=>JSON.parse(JSON.stringify(v));
function initialData(type){if(type==="CHECKLIST")return{width:280,height:220,items:[{id:uid("item"),label:"Novo item",checked:false,level:0}]};if(type==="IMAGE")return{width:240,height:180,label:"Imagem",src:""};if(type==="EMBED")return{width:420,height:300,url:""};if(type==="CALCULATOR")return{width:260,height:340};return{width:240,height:170,label:"Novo texto"};}
function textEditing(e){return isInput(e)}
function clockText(){return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",dateStyle:"short",timeStyle:"medium"}).format(new Date())}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function imageDimensions(src){return new Promise(resolve=>{const i=new Image();i.onload=()=>resolve({width:i.naturalWidth,height:i.naturalHeight});i.onerror=()=>resolve({width:240,height:180});i.src=src})}

export default function MapEditor({mapa,config:initialConfig}){
 const {user,logout,updateUser}=useContext(AuthContext);const rf=useReactFlow();
 const imageInput=useRef(null),replaceImageNode=useRef(null),saveTimer=useRef(null),saveQueue=useRef(Promise.resolve());
 const past=useRef([]),future=useRef([]),pending=useRef(null),historyTimer=useRef(null),transaction=useRef(null),leaving=useRef(false);
 const [config,setConfig]=useState(initialConfig||{});const theme=useMemo(()=>resolveTheme(config),[config]);
 const initialNodes=useMemo(()=>mapa.nodes.map(n=>({id:String(n.id),type:n.type||"TEXT",position:n.position||{x:100,y:100},data:{...initialData(n.type||"TEXT"),...(n.data||{}),imageDeformable:!!config.imagem_deformavel}})),[mapa.nodes,config.imagem_deformavel]);
 const initialEdges=useMemo(()=>mapa.edges.map(e=>({...e,id:String(e.id),source:String(e.source),target:String(e.target),sourceHandle:e.sourceHandle||"right-source",targetHandle:e.targetHandle||"left-target",style:EDGE_STYLE})),[mapa.edges]);
 const [nodes,setNodesState]=useState(initialNodes),[edges,setEdgesState]=useState(initialEdges);const nodesRef=useRef(initialNodes),edgesRef=useRef(initialEdges);
 const [editingNodeId,setEditingNodeId]=useState(null),[editingEdgeId,setEditingEdgeId]=useState(null),[focusedNodeId,setFocusedNodeId]=useState(null);
 const [settingsOpen,setSettingsOpen]=useState(false),[addOpen,setAddOpen]=useState(false),[clock,setClock]=useState(clockText()),[noteOpen,setNoteOpen]=useState(!!mapa.nota_flutuante),[note,setNote]=useState(mapa.nota_flutuante||"");
 const [searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(""),[searchIndex,setSearchIndex]=useState(0);
 const [context,setContext]=useState(null),[clipboard,setClipboard]=useState([]),[clipboardOpen,setClipboardOpen]=useState(false),[dragSelect,setDragSelect]=useState(null),[imageDrag,setImageDrag]=useState(false);
 const setNodes=useCallback(u=>setNodesState(c=>{const n=typeof u==="function"?u(c):u;nodesRef.current=n;return n}),[]),setEdges=useCallback(u=>setEdgesState(c=>{const n=typeof u==="function"?u(c):u;edgesRef.current=n;return n}),[]);
 useEffect(()=>{document.documentElement.style.setProperty("--bw-accent",theme.primary);document.documentElement.style.setProperty("--bw-bg",theme.secondary)},[theme]);
 useEffect(()=>{const i=setInterval(()=>setClock(clockText()),1000);return()=>clearInterval(i)},[]);
 useEffect(()=>{if(initialConfig)setConfig(initialConfig)},[initialConfig]);
 const capture=useCallback(()=>({nodes:clone(payload(nodesRef.current,edgesRef.current).nodes),edges:clone(payload(nodesRef.current,edgesRef.current).edges)}),[]);
 const serial=x=>JSON.stringify(x);
 const pushHistory=useCallback((item,compare=true)=>{if(compare&&serial(item)===serial(capture()))return;if(!past.current.length||serial(past.current[past.current.length-1])!==serial(item))past.current.push(item);if(past.current.length>HISTORY_LIMIT)past.current.shift();future.current=[]},[capture]);
 const commitHistory=useCallback(()=>{if(historyTimer.current)clearTimeout(historyTimer.current);historyTimer.current=null;if(pending.current){pushHistory(pending.current);pending.current=null}},[pushHistory]);
 const beginHistory=useCallback(()=>{if(!pending.current&&!transaction.current)pending.current=capture();if(historyTimer.current)clearTimeout(historyTimer.current);historyTimer.current=setTimeout(commitHistory,DATA_HISTORY_DELAY)},[capture,commitHistory]);
 const beginTransaction=useCallback(()=>{commitHistory();if(!transaction.current)transaction.current=capture()},[capture,commitHistory]);
 const finishTransaction=useCallback(()=>{if(transaction.current){pushHistory(transaction.current);transaction.current=null}},[pushHistory]);
 const undo=useCallback(()=>{finishTransaction();commitHistory();const p=past.current.pop();if(!p)return;future.current.push(capture());setNodes(p.nodes);setEdges(p.edges)},[capture,commitHistory,finishTransaction,setEdges,setNodes]);
 const redo=useCallback(()=>{commitHistory();const n=future.current.pop();if(!n)return;past.current.push(capture());setNodes(n.nodes);setEdges(n.edges)},[capture,commitHistory,setEdges,setNodes]);
 const center=useCallback(()=>rf.screenToFlowPosition({x:innerWidth/2,y:innerHeight/2}),[rf]);
 const updateNodeData=useCallback((id,partial)=>{beginHistory();setNodes(ns=>ns.map(n=>n.id===id?{...n,data:{...n.data,...partial}}:n))},[beginHistory,setNodes]);
 const resizeNode=useCallback((id,partial)=>setNodes(ns=>ns.map(n=>n.id===id?{...n,data:{...n.data,...partial}}:n)),[setNodes]);
 const enterEdit=useCallback(id=>{setFocusedNodeId(id);setEditingNodeId(id);setEditingEdgeId(null);setContext(null)},[]);
 const leaveEdit=useCallback(()=>{commitHistory();setEditingNodeId(null);setEditingEdgeId(null)},[commitHistory]);
 const createNode=useCallback((type,pos,data={})=>{pushHistory(capture(),false);const n={id:uid("node"),type,position:pos||center(),data:{...initialData(type),...data}};setNodes(ns=>[...ns,n]);setFocusedNodeId(n.id);setEditingNodeId(n.id);setAddOpen(false)},[capture,center,pushHistory,setNodes]);
 const addNode=useCallback(type=>{createNode(type,{...center(),x:center().x+(nodesRef.current.length%5)*25,y:center().y+(nodesRef.current.length%5)*25})},[center,createNode]);
 const createImage=useCallback(async(file,pos)=>{if(!file?.type?.startsWith("image/"))return alert("Escolha uma imagem válida.");if(file.size>IMAGE_MAX_BYTES)return alert("Imagem muito grande. Limite de 4 MB.");const src=await fileData(file);const dim=await imageDimensions(src);const max=420;const scale=Math.min(1,max/dim.width);createNode("IMAGE",pos,{label:file.name,src,mimeType:file.type,size:file.size,naturalWidth:dim.width,naturalHeight:dim.height,width:Math.max(40,Math.round(dim.width*scale)),height:Math.max(40,Math.round(dim.height*scale))})},[createNode]);
 const replaceImage=useCallback(async file=>{const id=replaceImageNode.current;if(!file||!id)return;const src=await fileData(file);const dim=await imageDimensions(src);updateNodeData(id,{src,label:file.name,naturalWidth:dim.width,naturalHeight:dim.height,width:Math.min(420,dim.width),height:Math.min(420,Math.round(dim.height*(Math.min(420,dim.width)/dim.width)))})},[updateNodeData]);
 const createEdge=useCallback(c=>{if(!c.source||!c.target||c.source===c.target)return;if(edgesRef.current.some(e=>e.source===c.source&&e.target===c.target&&e.sourceHandle===c.sourceHandle&&e.targetHandle===c.targetHandle))return;pushHistory(capture(),false);setEdges(es=>addEdge({...c,id:uid("edge"),style:EDGE_STYLE,label:""},es))},[capture,pushHistory,setEdges]);
 const removeNode=useCallback(id=>{pushHistory(capture(),false);setNodes(ns=>ns.filter(n=>n.id!==id));setEdges(es=>es.filter(e=>e.source!==id&&e.target!==id));setContext(null)},[capture,pushHistory,setEdges,setNodes]);
 const removeEdge=useCallback(id=>{pushHistory(capture(),false);setEdges(es=>es.filter(e=>e.id!==id));setContext(null)},[capture,pushHistory,setEdges]);
 const selectedNodes=nodes.filter(n=>n.selected),selectedEdges=edges.filter(e=>e.selected);
 const copySelection=useCallback(async()=>{const ns=nodesRef.current.filter(n=>n.selected),es=edgesRef.current.filter(e=>e.selected);if(!ns.length&&!es.length&&focusedNodeId){const n=nodesRef.current.find(x=>x.id===focusedNodeId);if(n)ns.push(n)}if(!ns.length&&!es.length)return;const item={id:uid("clip"),label:ns.length+es.length>1?"múltiplos itens":ns[0]?.type==="IMAGE"?"imagem":(ns[0]?.data?.label||"texto").slice(0,80),nodes:clone(ns.map(n=>({id:n.id,type:n.type,position:n.position,data:cleanData(n.data)}))),edges:clone(es.map(e=>({id:e.id,source:e.source,target:e.target,sourceHandle:e.sourceHandle,targetHandle:e.targetHandle,label:e.label||""}))),kind:ns.length+es.length>1?"multi":ns[0]?.type||"TEXT"};
  try{if(ns.length===1&&ns[0].type==="TEXT")await navigator.clipboard?.writeText(ns[0].data?.label||"")}catch{} setClipboard(c=>config.historico_clipboard_ativo===false?c:[item,...c.filter(x=>x.id!==item.id)].slice(0,6));
 },[config.historico_clipboard_ativo,focusedNodeId]);
 const pasteItem=useCallback(item=>{if(!item)return;pushHistory(capture(),false);const map=new Map();const ns=item.nodes.map(n=>{const id=uid("node");map.set(n.id,id);return{...clone(n),id,position:{x:n.position.x+40,y:n.position.y+40}}});const es=item.edges.filter(e=>map.has(e.source)&&map.has(e.target)).map(e=>({...e,id:uid("edge"),source:map.get(e.source),target:map.get(e.target),style:EDGE_STYLE}));setNodes(c=>[...c,...ns]);setEdges(c=>[...c,...es]);if(ns[0])setFocusedNodeId(ns[0].id);setClipboard(c=>[item,...c.filter(x=>x.id!==item.id)].slice(0,6))},[capture,pushHistory,setEdges,setNodes]);
 const deleteSelected=useCallback(()=>{const ids=new Set(nodesRef.current.filter(n=>n.selected).map(n=>n.id));const eids=new Set(edgesRef.current.filter(e=>e.selected).map(e=>e.id));if(!ids.size&&!eids.size)return;pushHistory(capture(),false);setNodes(ns=>ns.filter(n=>!ids.has(n.id)));setEdges(es=>es.filter(e=>!eids.has(e.id)&&!ids.has(e.source)&&!ids.has(e.target)) )},[capture,pushHistory,setEdges,setNodes]);
 const results=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return[];return nodes.filter(n=>n.type==="TEXT"||n.type==="CHECKLIST").filter(n=>{const t=n.type==="TEXT"?n.data?.label||"":(n.data?.items||[]).map(i=>i.label).join(" ");return t.toLowerCase().includes(q)}).map(n=>n.id)},[nodes,search]);
 useEffect(()=>{if(!results.length)return;setSearchIndex(i=>Math.min(i,results.length-1));const id=results[searchIndex]||results[0];const n=nodes.find(x=>x.id===id);if(n)rf.setCenter(n.position.x+(Number(n.data?.width)||240)/2,n.position.y+(Number(n.data?.height)||170)/2,{zoom:rf.getViewport().zoom,duration:250})},[results,searchIndex,rf,nodes]);
 const saveQueue=useCallback(data=>{const next=saveQueue.current.catch(()=>{}).then(()=>salvarMapa(mapa.id,data));saveQueue.current=next;return next},[mapa.id]);
 const handleWheel=useCallback(e=>{if(e.target.closest?.("textarea,input,button,select"))return;e.preventDefault();const v=rf.getViewport();const rect=e.currentTarget.getBoundingClientRect();if(e.ctrlKey){const factor=e.deltaY<0?1.08:.92;const z=Math.min(4,Math.max(.2,v.zoom*factor));const px=e.clientX-rect.left,py=e.clientY-rect.top;rf.setViewport({x:px-(px-v.x)*(z/v.zoom),y:py-(py-v.y)*(z/v.zoom),zoom:z});return}if(e.shiftKey){rf.setViewport({...v,x:v.x-e.deltaY});return}rf.setViewport({...v,y:v.y-e.deltaY})},[rf]);
 const saveSettings=useCallback(async(patch)=>{const c=await atualizarPreferenciasUsuario(patch);setConfig(c.configuracao||c);updateUser({configuracao:c.configuracao||c});return c},[updateUser]);
 const saveNote=useCallback(async(v)=>{setNote(v);await salvarConfiguracaoMapa(mapa.id,{nota_flutuante:v})},[mapa.id]);
 useEffect(()=>{if(leaving.current)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>saveQueue(payload(nodes,edges)).catch(console.error),1000);return()=>clearTimeout(saveTimer.current)},[nodes,edges,saveQueue]);
 useEffect(()=>{const h=async e=>{const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(mod&&!e.altKey){if(k==="f"&&!textEditing(e)){e.preventDefault();setSearchOpen(true);setTimeout(()=>document.querySelector(".bw-search-input")?.focus(),0);return}if(k==="z"&&!e.shiftKey&&!textEditing(e)){e.preventDefault();undo();return}if((k==="y"||(k==="z"&&e.shiftKey))&&!textEditing(e)){e.preventDefault();redo();return}if(k==="c"&&!textEditing(e)){e.preventDefault();await copySelection();return}if(k==="v"&&!textEditing(e)){e.preventDefault();const item=clipboard[0];if(item)pasteItem(item);return}}if(e.key==="Delete"&&!textEditing(e)){e.preventDefault();deleteSelected();return}if(e.key==="Escape"){setContext(null);setSearchOpen(false);setSettingsOpen(false);leaveEdit()}};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[clipboard,copySelection,deleteSelected,leaveEdit,pasteItem,redo,undo]);
 useEffect(()=>{let timer=null;const down=e=>{if(e.pointerType!=="touch")return;const nodeEl=e.target.closest?.(".react-flow__node");const edgeEl=e.target.closest?.(".react-flow__edge");if(!nodeEl&&!edgeEl)return;timer=setTimeout(()=>{const id=nodeEl?.getAttribute("data-id")||edgeEl?.getAttribute("data-id");if(nodeEl&&id){const n=nodesRef.current.find(x=>x.id===id);if(n)setContext({x:e.clientX,y:e.clientY,nodeId:id})}else if(edgeEl&&id){setContext({x:e.clientX,y:e.clientY,edgeId:id})}},5000)};const clear=()=>{if(timer){clearTimeout(timer);timer=null}};window.addEventListener("pointerdown",down);window.addEventListener("pointerup",clear);window.addEventListener("pointercancel",clear);window.addEventListener("pointermove",clear);return()=>{clear();window.removeEventListener("pointerdown",down);window.removeEventListener("pointerup",clear);window.removeEventListener("pointercancel",clear);window.removeEventListener("pointermove",clear)}},[]);
 useEffect(()=>{const onDown=e=>{if(e.button===2){const pane=!e.target.closest(".react-flow__node,.react-flow__edge,.bw-sticky,.bw-context-menu");if(pane){const start={x:e.clientX,y:e.clientY};setDragSelect({start,current:start});const move=ev=>setDragSelect(d=>d?{...d,current:{x:ev.clientX,y:ev.clientY}}:d);const up=ev=>{setDragSelect(d=>{if(!d)return null;const a=Math.min(d.start.x,d.current.x),b=Math.max(d.start.x,d.current.x),c=Math.min(d.start.y,d.current.y),dd=Math.max(d.start.y,d.current.y);const v=rf.getViewport();setNodes(ns=>ns.map(n=>{const w=Number(n.data?.width)||240,h=Number(n.data?.height)||170;const sx=n.position.x*v.zoom+v.x,sy=n.position.y*v.zoom+v.y;const hit=sx<b&&sx+w*v.zoom>a&&sy<dd&&sy+h*v.zoom>c;return hit?{...n,selected:true}:n}));return null});window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}}};window.addEventListener("pointerdown",onDown);return()=>window.removeEventListener("pointerdown",onDown)},[rf,setNodes]);
 const nodeContext=(e,n)=>{e.preventDefault();e.stopPropagation();setContext({x:e.clientX,y:e.clientY,nodeId:n.id})};
 const edgeContext=(e,e0)=>{e.preventDefault();e.stopPropagation();setContext({x:e.clientX,y:e.clientY,edgeId:e0.id})};
 const paneClick=()=>{setContext(null);setClipboardOpen(false);setSettingsOpen(false);setAddOpen(false);setFocusedNodeId(null);if(searchOpen)setSearchOpen(false);leaveEdit()};
 const nodeClick=(e,n)=>{if(e.nativeEvent?.pointerType==="touch"&&editingNodeId){setNodes(ns=>ns.map(x=>x.id===n.id?{...x,selected:!x.selected}:x));return}setFocusedNodeId(n.id)};
 const nodeDouble=(e,n)=>{e.stopPropagation();enterEdit(n.id)};
 const onChanges=changes=>setNodes(ns=>applyNodeChanges(changes,ns));
 const edgeChanges=changes=>{if(changes.some(c=>c.type==="remove"))pushHistory(capture(),false);setEdges(es=>applyEdgeChanges(changes,es))};
 const onResizeConfig=async(k,v)=>{setConfig(c=>({...c,[k]:v}));await saveSettings({[k]:v})};
 const chooseTheme=async(name)=>{const next={...config,cor_mapa:name};setConfig(next);updateUser({configuracao:next});await saveSettings({cor_mapa:name})};
 const contextNode=nodes.find(n=>n.id===context?.nodeId),contextEdge=edges.find(e=>e.id===context?.edgeId);
 return <div className="bw-map-root" style={{background:theme.secondary}} onWheel={handleWheel} onContextMenu={e=>e.preventDefault()} onClick={e=>{if(e.target===e.currentTarget)paneClick()}} onDragOver={e=>{if([...e.dataTransfer.types].includes("Files")){e.preventDefault();setImageDrag(true)}}} onDragLeave={()=>setImageDrag(false)} onDrop={async e=>{e.preventDefault();setImageDrag(false);const f=[...e.dataTransfer.files].find(x=>x.type.startsWith("image/"));if(f)await createImage(f,rf.screenToFlowPosition({x:e.clientX,y:e.clientY}))}}>
  {searchOpen&&<div className="bw-search-sticky"><input className="bw-search-input" value={search} onChange={e=>{setSearch(e.target.value);setSearchIndex(0)}} placeholder="pesquisar no mapa..."/><button onClick={()=>setSearchIndex(i=>results.length?(i-1+results.length)%results.length:0)}>←</button><span>{results.length?`${searchIndex+1}/${results.length}`:"0/0"}</span><button onClick={()=>setSearchIndex(i=>results.length?(i+1)%results.length:0)}>→</button></div>}
  <div className="bw-topbar bw-sticky"><div style={{position:"relative"}}><button className="bw-toolbar-button" onClick={()=>setAddOpen(v=>!v)}>+ adicionar nó</button>{addOpen&&<div className="bw-node-menu"><button onClick={()=>addNode("TEXT")}>caixa de texto</button><button onClick={()=>addNode("CHECKLIST")}>lista</button><button onClick={()=>imageInput.current?.click()}>imagem</button><button onClick={()=>addNode("EMBED")}>embed</button><button onClick={()=>addNode("CALCULATOR")}>calculadora</button></div>}</div><input ref={imageInput} type="file" accept="image/*" hidden onChange={async e=>{const f=e.target.files?.[0];e.target.value="";if(replaceImageNode.current){await replaceImage(f);replaceImageNode.current=null}else if(f)await createImage(f)}}/><button className="bw-toolbar-button bw-logout" onClick={async()=>{leaving.current=true;commitHistory();await saveQueue(payload(nodesRef.current,edgesRef.current)).catch(()=>{});logout()}}>salvar e sair</button></div>
  {config.nota_flutuante_ativa!==false&&<div className={`bw-floating-note bw-sticky ${noteOpen?"open":""}`} onClick={e=>e.stopPropagation()}>{noteOpen?<textarea autoFocus value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>{setNoteOpen(false);saveNote(note)}} placeholder="nota rápida..."/>:<button onClick={()=>setNoteOpen(true)}>✎</button>}</div>}
  {config.relogio_ativo!==false&&<div className="bw-map-clock bw-sticky">{clock}</div>}
  {config.historico_clipboard_ativo!==false&&<div className={`bw-clipboard ${clipboardOpen?"open":""}`} onMouseEnter={()=>setClipboardOpen(true)} onClick={e=>e.stopPropagation()}><button onClick={()=>setClipboardOpen(v=>!v)} className="bw-clipboard-peek">▣</button>{clipboardOpen&&<div className="bw-clipboard-list">{clipboard.length?clipboard.map(i=><button key={i.id} onClick={()=>pasteItem(i)}>{i.label}</button>):<span>clipboard vazio</span>}</div>}</div>}
  <button className="bw-config-sticky bw-sticky" onClick={e=>{e.stopPropagation();setSettingsOpen(v=>!v)}}>⚙</button>
  {settingsOpen&&<div className="bw-config-panel bw-sticky" onClick={e=>e.stopPropagation()}><strong>CONFIG</strong><label>tema<select value={config.cor_mapa||"BRAINWEB"} onChange={e=>chooseTheme(e.target.value)}>{Object.keys(THEMES).map(k=><option key={k} value={k}>{THEMES[k].name}</option>)}</select></label>{[1,2].map(i=><React.Fragment key={i}><label>custom {i} primária<input value={config[`custom_${i}_primaria`]||"#48abb3"} onChange={e=>setConfig(c=>({...c,[`custom_${i}_primaria`]:e.target.value}))} onBlur={()=>saveSettings({[`custom_${i}_primaria`]:config[`custom_${i}_primaria`]})}/></label><label>custom {i} secundária<input value={config[`custom_${i}_secundaria`]||"#0f2f33"} onChange={e=>setConfig(c=>({...c,[`custom_${i}_secundaria`]:e.target.value}))} onBlur={()=>saveSettings({[`custom_${i}_secundaria`]:config[`custom_${i}_secundaria`]})}/></label></React.Fragment>)}<label><input type="checkbox" checked={config.historico_clipboard_ativo!==false} onChange={e=>onResizeConfig("historico_clipboard_ativo",e.target.checked)}/> histórico de clipboard</label><label><input type="checkbox" checked={!!config.imagem_deformavel} onChange={e=>onResizeConfig("imagem_deformavel",e.target.checked)}/> deformar imagens livremente</label><label><input type="checkbox" checked={config.nota_flutuante_ativa!==false} onChange={e=>onResizeConfig("nota_flutuante_ativa",e.target.checked)}/> nota flutuante</label><label><input type="checkbox" checked={config.relogio_ativo!==false} onChange={e=>onResizeConfig("relogio_ativo",e.target.checked)}/> relógio</label></div>}
  {context&&<div className="bw-context-menu" style={{left:context.x,top:context.y}} onClick={e=>e.stopPropagation()}>{contextNode&&<>{<button onClick={()=>removeNode(contextNode.id)}>EXCLUIR</button>}{contextNode.type==="TEXT"&&<div className="bw-color-grid">{["default","green","yellow","red","white","transparent"].map(c=><button key={c} title={c} style={{background:c==="default"?theme.primary:c==="green"?"#34d46a":c==="yellow"?"#f1d44b":c==="red"?"#f05252":c==="white"?"#fff":"rgba(255,255,255,.3)"}} onClick={()=>{updateNodeData(contextNode.id,{textColor:c});setContext(null)}}/> )}</div>}{contextNode.type==="IMAGE"&&<><button onClick={()=>{replaceImageNode.current=contextNode.id;imageInput.current?.click();setContext(null)}}>TROCAR IMAGEM</button><button onClick={()=>{const w=Number(contextNode.data.naturalWidth)||240,h=Number(contextNode.data.naturalHeight)||180;updateNodeData(contextNode.id,{width:Math.min(420,w),height:Math.min(420,h)});setContext(null)}}>RESETAR DIMENSÕES</button></>}{contextNode.type==="CHECKLIST"&&<button onClick={()=>{const all=(contextNode.data.items||[]).every(i=>i.checked);updateNodeData(contextNode.id,{items:(contextNode.data.items||[]).map(i=>({...i,checked:!all}))});setContext(null)}}>MARCAR/DESMARCAR TODOS</button>}{contextNode.type==="EMBED"&&<button onClick={()=>enterEdit(contextNode.id)}>TROCAR LINK</button>}</>}{contextEdge&&<button onClick={()=>removeEdge(contextEdge.id)}>EXCLUIR</button>}</div>}
  {imageDrag&&<div className="bw-image-drop">solte a imagem para criar um nó</div>}
  {dragSelect&&<div className="bw-selection-box" style={{left:Math.min(dragSelect.start.x,dragSelect.current.x),top:Math.min(dragSelect.start.y,dragSelect.current.y),width:Math.abs(dragSelect.current.x-dragSelect.start.x),height:Math.abs(dragSelect.current.y-dragSelect.start.y)}}/>}
  <ReactFlow nodes={nodes.map(n=>({...n,data:{...n.data,editing:editingNodeId===n.id,imageDeformable:!!config.imagem_deformavel,onChange:updateNodeData,onResize:resizeNode,onResizeStart:beginTransaction,onResizeEnd:finishTransaction}}))} edges={edges.map(e=>({...e,style:EDGE_STYLE}))} nodeTypes={nodeTypes} onNodesChange={onChanges} onEdgesChange={edgeChanges} onConnect={createEdge} onNodeClick={nodeClick} onNodeDoubleClick={nodeDouble} onNodeContextMenu={nodeContext} onEdgeContextMenu={edgeContext} onPaneClick={paneClick} onPaneContextMenu={e=>e.preventDefault()} onNodeDragStart={beginTransaction} onNodeDragStop={finishTransaction} onEdgeDoubleClick={(e,e0)=>{e.stopPropagation();setEditingEdgeId(e0.id)}} onEdgeClick={(e,e0)=>{e.stopPropagation();setEditingEdgeId(e0.id)}} selectionOnDrag selectNodesOnDrag elementsSelectable nodesConnectable nodesDraggable panOnDrag zoomOnScroll={false} zoomOnPinch deleteKeyCode={null} fitView defaultEdgeOptions={{style:EDGE_STYLE,type:"default"}} connectionLineStyle={EDGE_STYLE}>
   <Background color="rgba(255,255,255,.12)" gap={24} size={1.5}/><Controls className="bw-flow-controls"/>
   {edges.map(e=>editingEdgeId===e.id&&<EdgeLabelRenderer key={e.id}><div className="bw-edge-editor" style={{left:0,top:0}}><input autoFocus value={e.label||""} onChange={ev=>{beginHistory();setEdges(es=>es.map(x=>x.id===e.id?{...x,label:ev.target.value}:x))}} onBlur={leaveEdit}/></div></EdgeLabelRenderer>)}
  </ReactFlow>
 </div>;
}